version: 2
jobs:
  one:
    docker:
      - image: unicef/etools:test-base-p3
    steps:
      - run:
          name: Check
          command: |
            env | sort
  two:
    docker:
      - image: unicef/etools:test-base-p3
    steps:
      - run:
          name: Check
          command: |
            env | sort
  three:
    docker:
      - image: unicef/etools:test-base-p3
    steps:
      - run:
          name: Check
          command: |
            env | sort


workflows:
  version: 2
  w1:
    jobs:
      - one:
          context: d111
      - two
  w2:
    jobs:
      - one:
          context: d110
      - two

#        filters:
#          branches:
#            only: feature/main_package_refactoring_step2
#      - one
#        context: d111

#        filters:
#          branches:
#            only: feature/main_package_refactoring_step2
#      - one
#        context: d111
