# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0013_auto_20161215_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelactivity',
            name='travel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='et2f.TravelType'),
        ),
    ]
