# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-02 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0062_intervention_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionplannedvisits',
            name='year',
            field=models.IntegerField(default=partners.models.get_current_year),
        ),
    ]
